server:
  port: 8899

#logging:
  #level:
    #org.springframework: DEBUG

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/playground
    username: burns
    password: P@ssw0rd
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  messages:
    basename: messages
  security:
    user:
      name: burns
      password: p@ssw0rd

management:
  endpoints:
    web:
      exposure:
        include: "*"
